### ISSUE TITLE
Choose an project idea

### ISSUE THREAD

**Issue by m33k** [vangourd/project_ideas#1]
A list of ideas are listed for us in https://github.com/vangourd/project_ideas/blob/master/README.md . Once we make a decision. We can create a directory for it or move it into it's own repo. We could also choose the top 3 ideas and work on one then work on the next one afterwards.

**Comment by vangourd** [comment]
Yeah I think we just maintain this repo as a list for future reference for whatever we decide to do next.

**Comment by vangourd** [comment]
So are we making new suggestions here? I really enjoy the game Settlers of Catan and could see myself really enjoying making a PyGame version for windows.

To the point that I would play it while at work I think lol.

**Comment by m33k** [comment]
Sounds good.  So here are the top 5 that interest me.

1. Web App
1. Shell script/utility
1. RaspberryPi/Arduino Project
1. Shell script/utility
1. JupyterNotebook/Numpy/Matlab

What are you top 5?

**Comment by vangourd** [comment]
1. Web App
2. GUI Programming
3. Shell script/utility
4. RaspberryPi
5. PyGame

**Comment by m33k** [comment]
I think we found our first project. Build a Web App. We could use [DJango](https://www.djangoproject.com/) or [Flask](https://palletsprojects.com/p/flask/) to help us.

**Comment by vangourd** [comment]
Okay great! 🎆🎇

Now what we need to come up with a Problem definition and then define some requirements.

**Comment by m33k** [comment]
That's a good point.

Here are two lists we could sort through specifically for Django.

https://realpython.com/intermediate-python-project-ideas/
https://www.pythoncircle.com/post/669/python-django-project-idea-for-beginners/

We should try to keep it simple so we can actually finish it.

**Comment by vangourd** [comment]
So here's a dumb one but something I've always thought of doing. 

A sorting tool for manual  prioritization of things. 

Basically like a flashcard system but it performs sorting algorithms for you and you just decide if item A or B is more important. Think like an eye doctor when they ask you if A or B. 

Then the app just compiles the list for you to re-sort your task manager.

**Comment by m33k** [comment]
We made a decision via our Slack convo. We choose to go with a GUI App. We will be making an mp3 player. The repo can be found in: https://github.com/vangourd/qtmp3player
